export const DESTINATION_COUNTRIES = [
  "Allemagne",
  "Autriche",
  "Belgique",
  "Bulgarie",
  "Canada",
  "Chypre",
  "Corée du Sud",
  "Croatie",
  "Danemark",
  "Dubai (EAU)",
  "Espagne",
  "Estonie",
  "Etats-Unis",
  "Finlande",
  "France",
  "Grece",
  "Hongrie",
  "Irlande",
  "Islande",
  "Italie",
  "Japon",
  "Lettonie",
  "Liechtenstein",
  "Lituanie",
  "Luxembourg",
  "Malte",
  "Monaco",
  "Norvege",
  "Nouvelle-Zelande",
  "Pays-Bas",
  "Pologne",
  "Portugal",
  "Qatar",
  "Republique tcheque",
  "Roumanie",
  "Royaume-Uni",
  "Singapour",
  "Slovaquie",
  "Slovenie",
  "Suede",
  "Suisse",
] as const;
